export const GET_COMPETITOR_REQUEST = "GET_COMPETITOR_REQUEST";
export const GET_COMPETITOR_SUCCESS = "GET_COMPETITOR_SUCCESS";
export const GET_COMPETITOR_FAILURE = "GET_COMPETITOR_FAILURE";

export const SET_COMPETITOR_REQUEST = "SET_COMPETITOR_REQUEST";
export const SET_COMPETITOR_SUCCESS = "SET_COMPETITOR_SUCCESS";
export const SET_COMPETITOR_FAILURE = "SET_COMPETITOR_FAILURE";